### ISSUE TITLE
slack.sh

### ISSUE THREAD

**Issue by OmarDarwish** [chernjie/poller#1]
Is the `slack.sh` [referenced here](https://github.com/chernjie/poller/blob/8804062518dc1d572096bcbc24ff812fa7b7246c/bin/poller.sh#L23) another project? If not, I'd love to take a peek at what it does!

**Comment by chernjie** [comment]
oh yeah it is just a curl command that takes the whole of the first argument as message. You can see [chat.postMessage](https://api.slack.com/methods/chat.postMessage) for details
